## We'll keep the link to DBT project here

from pathlib import Path
from dagster_dbt import DbtProject

#This code references the DBT project in the analytics folder
dbt_project = DbtProject(
  project_dir=Path(__file__).joinpath("..", "analytics").resolve(),
)

dbt_project.prepare_if_dev()
# This will create the manifest file if it doesn't exist
# and will update it if it does.
# This is useful for development purposes only.
# In production, you should use the manifest file generated by DBT.


